### ISSUE TITLE
Incorrect getExcludesPatterns

### ISSUE THREAD

**Issue by jeffmaury** [mark2b/maven-jet-plugin#1]
The method getExcudesPatterns incorrectly returns includeTemplates instead  of excludeTemplates

The code from master branch:

```
        @SuppressWarnings("unchecked")
        public Set<String> getExcludesPatterns() {
                if (excludeTemplates == null || excludeTemplates.isEmpty()) {
                        return Collections.EMPTY_SET;
                }
                return includeTemplates;
        }
```

**Comment by mark2b** [comment]
Thanks, can you fix it (and the second one too). If no, please let me known I will fix it in the nearest future.

**Comment by jeffmaury** [comment]
I will fork and send you the pull request
